#!/usr/bin/env bash

# Adapted from https://github.com/bazelbuild/stardoc/blob/master/test/diff_test_runner.sh.

set -e -u -o pipefail

actual_file=$1
golden_file=$2

# NB: diff fails when there's a difference to report.
diff_output="$(diff ${golden_file} ${actual_file})" || :
if [ -n "${diff_output}" ]; then
  echo "FAIL: Actual output differs from expected golden content:"
  echo "${diff_output}"
  exit 1
else
  echo "SUCCESS: Actual output matches expected golden content."
fi
