# We must accommodate loading this file from repositories generated by
# our repository rules.
visibility("public")

_TOOLS_BY_RELEASE = {
    "v0.5.0-beta.5": {
        struct(os = "darwin", arch = "amd64"): "a42fb422c7fd8ea0b8b1bb8289107a418da6ddaf0e37fd6aca1dc7d6fd7b583c",
        struct(os = "darwin", arch = "arm64"): "6fb64fdf2338622e5a3bf46b7abc08611386faf3b6807e5cb2543dffa73c2609",
        struct(os = "linux", arch = "amd64"): "f2f4590ff33c9d5730973c97c2d75a17f2447bae8b547915a60f55e61c5ae298",
        struct(os = "linux", arch = "arm64"): "0f2df97ba7aa6e4bbb361cf5e70b17f210efe321f1be54791d272f18e0761a6d",
        struct(os = "windows", arch = "amd64"): "8e927f05f1fb82215b7fbdc03cb9a19bc882603ea30ba0f57e30865c654269da",
        struct(os = "windows", arch = "arm64"): "9066faea531bbeff3e63d165614a1b17f2ce988df5011a2eeb6ccb09f91d67aa",
    },
    "v0.5.0-beta.2": {
        struct(os = "darwin", arch = "amd64"): "3e09097396c513795fcfe58adeb648cc860091ce72a14404b5c5594c1e4b063f",
        struct(os = "darwin", arch = "arm64"): "d0f0e27f4086e283de52acf3367c3a3671843f3dae9b1fc42d54c5311d529fc0",
        struct(os = "linux", arch = "amd64"): "2442309d506008061414f13625633370b904cd0b2a4e4b157f33d3b773584640",
        struct(os = "linux", arch = "arm64"): "de7d476a3775aa860a991edf1a7cef4cb223b28e15145ec62afb00c0ee569c1c",
        struct(os = "windows", arch = "amd64"): "7aa4fad5cdc97c78dacc5ee294c6f5faaf057d870b495ef91fb0e3b80c529931",
        struct(os = "windows", arch = "arm64"): "716a0a6bbf4e086a2defc9ecbe2d95f1f7f01888265e9cc5763b50043d827245",
    },
    "v0.5.0-beta.1": {
        struct(os = "darwin", arch = "amd64"): "936dedc7f1630821956bae5d8aab7b0f0c5c63ea56d329c5030b59fb2613b0cd",
        struct(os = "darwin", arch = "arm64"): "9fa583fcdd45e4f446388aca1f50acc213c2186fe0491e21448051eed0d2b2a2",
        struct(os = "linux", arch = "amd64"): "8fba35aa3aaa9ab7ec012f6522d006125168605c24fe93e14f6aec5789f99df0",
        struct(os = "linux", arch = "arm64"): "4d9c36b4b491ba4a4bf851eda384402bd98e4ba0b54aeccedc51067644a43848",
        struct(os = "windows", arch = "amd64"): "015dac67700ebed36babb9b72d1823a7590bbfabf929dd7df308b44c3ed532c1",
        struct(os = "windows", arch = "arm64"): "6002984bfec5362572eaf7995b19bf55c0085f6e9171614e2f4b8ad3c84dfc6e",
    },
    "v0.4.3": {
        struct(os = "darwin", arch = "amd64"): "1161254cf38b928b87a7ac1552dc2e12e6c5da298f9ce370d80e5518ddb6513d",
        struct(os = "darwin", arch = "arm64"): "3d84b85a7288f94301a4726dcf95b2d92c8ff796c4d45c4733fbdcc04ceaf21d",
        struct(os = "linux", arch = "amd64"): "5e7ecb614b5926acfc36eb1258800391ab7c6e6e026fa7cacbfe92006bac895c",
        struct(os = "linux", arch = "arm64"): "a8c3f4140d18c324cc69f5de4df0566e529e1636cff340095a42475799bf3fed",
        struct(os = "windows", arch = "amd64"): "67f76e36809565c1396cea1b44978d98807d980d55a7ddc3979396d34fac1037",
        struct(os = "windows", arch = "arm64"): "a87573f32213a72d763dd624a1b63414e3d862ae4cef0b2698652aef380ebe60",
    },
    "v0.4.2": {
        struct(os = "darwin", arch = "amd64"): "3da1576d36950c64acb7d7a7b80f34e5935ac76b9ff607517981eef44a88a31b",
        struct(os = "darwin", arch = "arm64"): "21fcfbe52beff7bae510bb6267fe33a5785039bd7d5f32e3c3222c55580dd85c",
        struct(os = "linux", arch = "amd64"): "d43cf77e54f42619d270b8e4c1836aec87304daf243449c503251e6943f7466a",
        struct(os = "linux", arch = "arm64"): "6515c1f1b6fc09d083be533019416b28abd91e5cdd8ef53cd0719a4b4b0cd1c7",
        struct(os = "windows", arch = "amd64"): "95be4cd6b04b6c729f4f85a551280378d8939773c2eaecd79c70f907b5cae847",
        struct(os = "windows", arch = "arm64"): "e03325656ca20d464307f68e3070d774af37e5777156ae983e166d7d7aed60df",
    },
}

_DEFAULT_TOOL_VERSION = "v0.4.3"

def known_release_versions():
    return _TOOLS_BY_RELEASE.keys()

CUEInfo = provider(
    doc = "Details pertaining to the CUE toolchain.",
    fields = {
        "tool": "CUE tool to invoke",
        "version": "This tool's released version name",
    },
)

CUEToolInfo = provider(
    doc = "Details pertaining to the CUE tool.",
    fields = {
        "binary": "CUE tool to invoke",
        "version": "This tool's released version name",
    },
)

def _cue_tool_impl(ctx):
    return [CUEToolInfo(
        binary = ctx.executable.binary,
        version = ctx.attr.version,
    )]

cue_tool = rule(
    implementation = _cue_tool_impl,
    attrs = {
        "binary": attr.label(
            mandatory = True,
            allow_single_file = True,
            executable = True,
            cfg = "exec",
            doc = "CUE tool to invoke",
        ),
        "version": attr.string(
            mandatory = True,
            doc = "This tool's released version name",
        ),
    },
)

def _toolchain_impl(ctx):
    tool = ctx.attr.tool[CUEToolInfo]
    toolchain_info = platform_common.ToolchainInfo(
        cueinfo = CUEInfo(
            tool = tool.binary,
            version = tool.version,
        ),
    )
    return [toolchain_info]

cue_toolchain = rule(
    implementation = _toolchain_impl,
    attrs = {
        "tool": attr.label(
            mandatory = True,
            providers = [CUEToolInfo],
            cfg = "exec",
            doc = "CUE tool to use for validating and exporting data.",
        ),
    },
)

# buildifier: disable=unnamed-macro
def declare_cue_toolchains(cue_tool):
    for version, platforms in _TOOLS_BY_RELEASE.items():
        for platform in platforms.keys():
            cue_toolchain(
                name = "{}_{}_{}".format(platform.os, platform.arch, version),
                tool = cue_tool,
            )

def _translate_host_platform(ctx):
    # NB: This is adapted from rules_go's "_detect_host_platform" function.
    os = ctx.os.name
    if os == "mac os x":
        os = "darwin"
    elif os.startswith("windows"):
        os = "windows"

    arch = ctx.os.arch
    if arch == "aarch64":
        arch = "arm64"
    elif arch == "x86_64":
        arch = "amd64"

    return os, arch

_MODULE_REPOSITORY_NAME = "rules_cue"
_CONTAINING_PACKAGE_PREFIX = "//cue/private/tools/cue"

def _download_tool_impl(ctx):
    if not ctx.attr.arch and not ctx.attr.os:
        os, arch = _translate_host_platform(ctx)
    else:
        if not ctx.attr.arch:
            fail('"os" is set but "arch" is not')
        if not ctx.attr.os:
            fail('"arch" is set but "os" is not')
        os, arch = ctx.attr.os, ctx.attr.arch
    version = ctx.attr.version

    sha256sum = _TOOLS_BY_RELEASE[version][struct(os = os, arch = arch)]
    if not sha256sum:
        fail('No CUE tool is available for OS "{}" and CPU architecture "{}" at version {}'.format(os, arch, version))
    ctx.report_progress('Downloading CUE tool for OS "{}" and CPU architecture "{}" at version {}.'.format(os, arch, version))
    ctx.download_and_extract(
        url = "https://github.com/cue-lang/cue/releases/download/{version}/cue_{version}_{os}_{arch}.{extension}".format(
            version = version,
            os = os,
            arch = arch,
            extension = "zip" if os == "windows" else "tar.gz",
        ),
        sha256 = sha256sum,
    )

    ctx.template(
        "BUILD.bazel",
        Label("{}:BUILD.tool.bazel".format(_CONTAINING_PACKAGE_PREFIX)),
        executable = False,
        substitutions = {
            "{containing_package_prefix}": "@{}{}".format(_MODULE_REPOSITORY_NAME, _CONTAINING_PACKAGE_PREFIX),
            "{extension}": ".exe" if os == "windows" else "",
            "{version}": version,
        },
    )
    return None

_download_tool = repository_rule(
    implementation = _download_tool_impl,
    attrs = {
        "arch": attr.string(),
        "os": attr.string(),
        "version": attr.string(
            values = _TOOLS_BY_RELEASE.keys(),
            default = _DEFAULT_TOOL_VERSION,
        ),
    },
)

# buildifier: disable=unnamed-macro
def declare_bazel_toolchains(version, toolchain_prefix):
    native.constraint_value(
        name = version,
        constraint_setting = "{}:tool_version".format(_CONTAINING_PACKAGE_PREFIX),
    )
    constraint_value_prefix = "@{}//cue/private/tools".format(_MODULE_REPOSITORY_NAME)
    for platform in _TOOLS_BY_RELEASE[version].keys():
        native.toolchain(
            name = "{}_{}_{}_toolchain".format(platform.os, platform.arch, version),
            exec_compatible_with = [
                "{}:cpu_{}".format(constraint_value_prefix, platform.arch),
                "{}:os_{}".format(constraint_value_prefix, platform.os),
            ],
            toolchain = toolchain_prefix + (":{}_{}_{}".format(platform.os, platform.arch, version)),
            toolchain_type = "@{}//tools/cue:toolchain_type".format(_MODULE_REPOSITORY_NAME),
        )

def _toolchains_impl(ctx):
    ctx.template(
        "BUILD.bazel",
        Label("{}:BUILD.toolchains.bazel".format(_CONTAINING_PACKAGE_PREFIX)),
        executable = False,
        substitutions = {
            "{containing_package_prefix}": "@{}{}".format(_MODULE_REPOSITORY_NAME, _CONTAINING_PACKAGE_PREFIX),
            "{tool_repo}": ctx.attr.tool_repo,
            "{version}": ctx.attr.version,
        },
    )

_toolchains_repo = repository_rule(
    implementation = _toolchains_impl,
    attrs = {
        "tool_repo": attr.string(mandatory = True),
        "version": attr.string(
            values = _TOOLS_BY_RELEASE.keys(),
            default = _DEFAULT_TOOL_VERSION,
        ),
    },
)

def download_tool(name, version = None):
    _download_tool(
        name = name,
        version = version,
    )
    _toolchains_repo(
        name = name + "_toolchains",
        tool_repo = name,
        version = version,
    )
