#!/usr/bin/env bash

# Copy-pasted from the Bazel Bash runfiles library v2.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e

function usage() {
  printf "usage: %s [-c cue_cache_directory] [-d cue_debug] [-i instance_path] [-m module_file] [-p package_name] cue_tool cue_subcommand extra_args_file packageless_files_file output_file [args...]\n" "$(basename "${0}")" 1>&2
  exit 2
}

cue_cache_directory=
cue_debug=
instance_path=
module_file=
package_name=

function parse_args() {
  while getopts c:d:i:m:p: name
  do
    case "${name}" in
      c) cue_cache_directory="${OPTARG}";;
      d) cue_debug="${OPTARG}";;
      i) instance_path="${OPTARG}";;
      h) usage;;
      m) module_file="${OPTARG}";;
      p) package_name="${OPTARG}";;
      ?) usage;;
    esac
  done
  if [ -n "${cue_cache_directory}" ] && [ ! -d "${cue_cache_directory}" ]; then
      printf "%s: specified CUE cache directory \"%s\" does not exist\n" "$(basename "${0}" "${cue_cache_directory}")" 1>&2
      exit 1
  fi
  if [ -n "${instance_path}" ] && [ -z "${module_file}" ]; then
      printf "%s: specifying a CUE instance path requires specifying a module path\n" "$(basename "${0}")" 1>&2
      exit 1
  fi
  if [ -n "${package_name}" ] && [ -z "${instance_path}" ]; then
      printf "%s: specifying a CUE package name requires specifying an instance path\n" "$(basename "${0}")" 1>&2
      exit 1
  fi
}

parse_args "${@}"
shift $((OPTIND - 1))

cue=$1; shift
subcommand=$1; shift
extra_args_file=$1; shift
packageless_files_file=$1; shift
output_file=$1; shift

oldwd="${PWD}"
packageless_file_args=()
qualifier=
while read -r line; do
  if [ -z "${line}" ]; then
    continue
  fi
  if [[ "${line}" =~ .+:$ ]]; then
    qualifier="${line}"
  else
    if [ -n "${qualifier}" ]; then
      packageless_file_args+=("${qualifier}")
      qualifier=
    fi
    packageless_file_args+=("${oldwd}/$(rlocation ${line})")
  fi
done < "${packageless_files_file}"
if [ -n "${qualifier}" ]; then
  echo >&2 "No file path followed qualifier \"${qualifier}\"."
  exit 1
fi

# NB: If we don't assign to packageless_file_args above in the loop,
# it winds up being undefined afterward.
if (( ${#packageless_file_args[@]} == 0 )); then
  packageless_file_args=()
fi

if [ -n "${module_file}" ]; then
  adjusted_module_file="$(rlocation ${module_file})"
  if [ -z "${adjusted_module_file}" ]; then
    echo >&2 "No runfile path available for module file path \"${module_file}\"."
    exit 1
  fi
  module_path="$(dirname $(dirname ${adjusted_module_file}))"
  cd "${module_path}"
fi

# Since we don't have access to the "HOME" environment variable here
# (barring use of the "--action-env" command-line flag), we must tell
# CUE where to store its cache explicitly.
if [ -n "${cue_cache_directory}" ]; then
  export CUE_CACHE_DIR="${cue_cache_directory}"
elif [ -z "${HOME:-}" ]; then
  cue_cache_directory="$(mktemp -d -t cue-XXXXXX)"
  trap "rm -rf '${cue_cache_directory}'" EXIT
  export CUE_CACHE_DIR="${cue_cache_directory}"
fi

if [ -n "${cue_debug}" ]; then
  export CUE_DEBUG="${cue_debug}"
fi

# NB: See https://stackoverflow.com/questions/7577052 for the odd
# treatment of the "packageless_file_args" array variable here,
# handling the case where the array winds up empty for lack of
# so-called "packageless files" being used as input. As we are
# uncertain of which Bash we'll wind up using, aim to work around as
# many of their mutually exclusive defects as possible.
"${oldwd}/${cue}" "${subcommand}" --outfile "${oldwd}/${output_file}" \
  ${instance_path}${package_name:+:${package_name}} \
  ${packageless_file_args[@]+"${packageless_file_args[@]}"} \
  $(< "${oldwd}/${extra_args_file}") \
  "${@-}"
